src/Entity/Propriete.php
<?php

namespace App\Entity;

use App\Entity\Options;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProprieteRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass=ProprieteRepository::class)
 * @Vich\Uploadable()
 */
class Propriete
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;
    
    /**
     * @var File|null
     * @Assert\Image(mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="propriete_images", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=100, max=400, minMessage="La surface doit etre superieur à 100m²", maxMessage="La surface doit etre inferieur à 400m²")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     * 
     */
    private $piece;

    /**
     * @ORM\Column(type="integer")
     * 
     */
    private $etage;

    /**
     * @ORM\Column(type="integer")
     * 
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $chauffage;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $codePostal;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vendu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToMany(targetEntity=Options::class, inversedBy="propriete")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;


    public function __construct()
    {
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPiece(): ?int
    {
        return $this->piece;
    }

    public function setPiece(int $piece): self
    {
        $this->piece = $piece;

        return $this;
    }

    public function getEtage(): ?int
    {
        return $this->etage;
    }

    public function setEtage(int $etage): self
    {
        $this->etage = $etage;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getChauffage(): ?string
    {
        return $this->chauffage;
    }

    public function setChauffage(string $chauffage): self
    {
        $this->chauffage = $chauffage;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getVendu(): ?bool
    {
        return $this->vendu;
    }

    public function setVendu(bool $vendu): self
    {
        $this->vendu = $vendu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPrixFormatter()
    {
        return number_format($this->prix,0,'.', '.');
    }

    public function getSlug() : string
    {
        $slugify = new Slugify(); 
        return $slugify->slugify($this->getTitre());  
    }

    /**
     * @return Collection|Options[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Options $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addPropriete($this);
        }

        return $this;
    }

    public function removeOption(Options $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removePropriete($this);
        }

        return $this;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null) : Propriete
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile ) {
            $this->updatedAt = new \DateTime();
        }
        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

}

src/Controller/Admin/AdminProprieteController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Propriete;
use App\Form\ProprieteType;
use App\Repository\ProprieteRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Liip\ImagineBundle\Imagine\Cache\CacheManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;

/**
 * @Route("/admin/propriete")
 */
class AdminProprieteController extends AbstractController
{
    /**
     * @Route("/", name="admin_propriete", methods={"GET"})
     */
    public function index(
        ProprieteRepository $proprieteRepository,
        PaginatorInterface $pagination,
        Request $request
    ): Response {
        $proprietes = $pagination->paginate(
            $proprieteRepository->All(),
            $request->query->getInt('page', 1),
            7
        );
        return $this->render('backoffice/admin_propriete/index.html.twig', [
            'current' => 'propriete',
            'proprietes' => $proprietes,

        ]);
    }

    /**
     * @Route("/new", name="admin_propriete_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $propriete = new Propriete();
        $form = $this->createForm(ProprieteType::class, $propriete);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $propriete->setCreatedAt(new \DateTime());
            $entityManager->persist($propriete);
            $entityManager->flush();
            $this->addFlash(
                'success',
                'vous venez d\'ajouter une nouvelle propriete'
            );
            return $this->redirectToRoute('admin_propriete', ['id' => $propriete->getId()]);
        }

        return $this->renderForm('backoffice/admin_propriete/new.html.twig', [
            'propriete' => $propriete,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="admin_propriete_show", methods={"GET"})
     */
    public function show(Propriete $propriete): Response
    {
        return $this->render('backoffice/admin_propriete/show.html.twig', [
            'propriete' => $propriete,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_propriete_edit", methods={"GET","POST"})
     */
    public function edit(
        Request $request,
        Propriete $propriete,
        CacheManager $cacheManager,
        UploaderHelper $helper
    ): Response {
        $form = $this->createForm(ProprieteType::class, $propriete);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($propriete->getImageFile() instanceof UploadedFile) {
                $cacheManager->remove($helper->asset($propriete, 'imageFile'));
            }
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash(
                'success',
                'propriete modifié avec success'
            );
            return $this->redirectToRoute('admin_propriete', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('backoffice/admin_propriete/edit.html.twig', [
            'propriete' => $propriete,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="admin_propriete_delete", methods={"POST"})
     */
    public function delete(
        Request $request,
        Propriete $propriete,
        CacheManager $cacheManager,
        UploaderHelper $helper
    ): Response {
        if ($this->isCsrfTokenValid('delete' . $propriete->getId(), $request->request->get('_token'))) {
            $cacheManager->remove($helper->asset($propriete, 'imageFile'));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($propriete);
            $entityManager->flush();
        }
        $this->addFlash(
           'alert',
           'vous venez de supprimer un bien'
        );
        return $this->redirectToRoute('admin_propriete',);
    }
}

templates/backoffice/admin_propriete/_delete_form.html.twig
<form method="post" action="{{ path('admin_propriete_delete', {'id': propriete.id}) }}"
    onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ propriete.id) }}">
    <button class="btn btn-danger btn-lg btn-flat mt-3">
        <i class="fas fa-trash fa-lg mr-2"></i>
        <font style="vertical-align: inherit;">
            <font style="vertical-align: inherit;">
                Supprimer
            </font>
        </font>

    </button>
</form>

templates/backoffice/admin_propriete/_form.html.twig
<section class="content">
    <div class="container-fluid">
        <div class="container">
            {{form_start(form)}}
            <div class="row form-group">
                <div class="col-8">
                    <div class="row mb-3">
                        {{form_row(form.titre)}}
                    </div>
                    <div class="row mb-3">
                        <div class="col-4">{{form_row(form.surface)}}</div>
                        <div class="col-4">{{form_row(form.piece)}}</div>
                        <div class="col-4">{{form_row(form.etage)}}</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-4">{{form_row(form.prix)}}</div>
                        <div class="col-4">{{form_row(form.chauffage)}}</div>
                        <div class="col-4">{{form_row(form.ville)}}</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-6">{{form_row(form.adresse)}}</div>
                        <div class="col-4">{{form_row(form.codePostal)}}</div>
                        <div class="col-2">{{form_row(form.vendu)}}</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-6">{{form_row(form.options)}}</div>
                        <div class="col-6">{{form_row(form.imageFile)}}</div>
                    </div>
                    <div class="row mb-3">
                        <div>
                            <button class="btn btn btn-success">{{ button_label|default('Enregistrer') }}</button>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    {{form_row(form.description)}}
                </div>
            </div>
            {{form_end(form)}}
        </div>
    </div>
    </div>
</section>

templates/backoffice/admin_propriete/edit.html.twig
{% extends "backoffice/base/base.html.twig" %}

{% block body %}
<div class="content-wrapper" style="min-height: 1761.5px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <h1>
                    <font style="vertical-align: inherit;">
                        <font style="vertical-align: inherit;">Modifier la propriété</font>
                    </font>
                </h1>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    {{ include('backoffice/admin_propriete/_form.html.twig',{'button_label': 'Mettre à jour'}) }}
{% endblock %}

templates/backoffice/admin_propriete/index.html.twig
{% extends "backoffice/base/base.html.twig" %}

{% block body %}
<div class="content-wrapper" style="min-height: 1761.5px;">
    {% for message in app.flashes('success') %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">Toutes les proprietes</font>
                        </font>
                    </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{path('admin_propriete_new')}}" class="btn btn-primary btn-sm">Nouvelle
                                propriété</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Toutes les propriétés</h3>

                <div class="card-tools">
                    <div class="pagination pagination-sm float-right mt-1">
                        {% do proprietes.setPageRange(4) %}
                        {{ knp_pagination_render(proprietes, 'vitrine/base/include/pagination.html.twig') }}
                    </div>
                </div>
            </div>
            <div class="card-body p-0" style="display: block;">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Titre
                            </th>
                            <th style="width: 30%">
                                Description
                            </th>
                            <th>
                                prix
                            </th>
                            <th style="width: 8%" class="text-center">
                                vendu
                            </th>
                            <th style="width: 20%" class="text-center">
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for propriete in proprietes %}
                        <tr>
                            <td>
                                #
                            </td>
                            <td>
                                <a>
                                    {{propriete.titre}}
                                </a>
                                <br>
                                <small>
                                    crée le : {{propriete.createdAt|date("d/m/Y")}}
                                </small>
                            </td>
                            <td>
                                {{propriete.Description | u.truncate(70,'...',false)}}
                            </td>
                            <td class="project_progress">
                                {{propriete.prixFormatter}} Fcfa
                            </td>
                            <td class="project-state">
                                {% if propriete.vendu == 1 %}
                                <span class="badge badge-success">Vendu</span>
                                {% elseif propriete.vendu == 0 %}
                                <span class="badge badge-warning">Non vendu</span>
                                {% endif %}
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="{{path('admin_propriete_show', {id: propriete.id})}}">
                                    <i class="fas fa-eye">
                                    </i>
                                    Voir
                                </a>
                                {% if propriete.vendu == 0 %}
                                <a class="btn btn-info btn-sm" href="{{path('admin_propriete_edit', {id: propriete.id})}}">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Editer
                                </a>
                                {% endif %}
                                <a class="btn btn-danger btn-sm" href="{{path('admin_propriete_delete',{id:propriete.id})}}">
                                    <i class="fas fa-trash">
                                    </i>
                                    Supp
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
</div>
{% endblock %}

templates/backoffice/admin_propriete/new.html.twig
{% extends "backoffice/base/base.html.twig" %}

{% block body %}
<div class="content-wrapper" style="min-height: 1761.5px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <h1>
                    <font style="vertical-align: inherit;">
                        <font style="vertical-align: inherit;">Ajouter une nouvelle propriété</font>
                    </font>
                </h1>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    {{ include('backoffice/admin_propriete/_form.html.twig') }}
{% endblock %}

templates/backoffice/admin_propriete/show.html.twig
{% extends "backoffice/base/base.html.twig" %}

{% block body %}
<div class="content-wrapper" style="min-height: 1761.5px;">
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card card-solid">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <h3 class="d-inline-block d-sm-none">{{propriete.titre}}</h3>
                            <div class="col-12">
                                {% if propriete.image %}
                                <img src="{{ vich_uploader_asset(propriete, 'imageFile') | imagine_filter('medium')}}" class="product-image"
                                    style="width: 100%; height:auto;">
                                {% else %}
                                <img src="{{ 'images/propriete/default.jpg' | imagine_filter('medium')}}" class="product-image"
                                    style="width: 100%; height:auto;">
                                {% endif %}
                            </div>
                            {% if propriete.vendu == 1 %}
                                <div class="col-12 bg-success rounded mt-4">
                                    <h3 class="text-center"><i class="fas fa-check-double"></i> VENDU</h3>
                                </div>
                            {% endif %}
                            <!-- <div class="col-12 product-image-thumbs">
                                <div class="product-image-thumb active"><img src="../../dist/img/prod-1.jpg"
                                        alt="Product Image"></div>
                                <div class="product-image-thumb"><img src="../../dist/img/prod-2.jpg"
                                        alt="Product Image"></div>
                                <div class="product-image-thumb"><img src="../../dist/img/prod-3.jpg"
                                        alt="Product Image"></div>
                                <div class="product-image-thumb"><img src="../../dist/img/prod-4.jpg"
                                        alt="Product Image"></div>
                                <div class="product-image-thumb"><img src="../../dist/img/prod-5.jpg"
                                        alt="Product Image"></div>
                            </div> -->
                        </div>
                        <div class="col-12 col-sm-6">
                            <h3 class="my-3">{{propriete.titre}}</h3>
                            <p>{{propriete.description}}</p>

                            <hr>
                            <h4>Caractéristiques</h4>
                            <div class="container mt-4">
                                <div class="row">
                                    <div class="col-md-8">
                                        <table class="table table-striped">
                                            <tr>
                                                <td class="h1">Caracteristique</td>
                                                <td class="h1">Specificite</td>
                                            </tr>
                                            <tr>
                                                <td>Surface habitable</td>
                                                <td>{{propriete.surface}} m²</td>
                                            </tr>
                                            <tr>
                                                <td>Pièces</td>
                                                <td>{{propriete.piece}}</td>
                                            </tr>
                                            <tr>
                                                <td>Etage</td>
                                                <td>{{propriete.etage}}</td>
                                            </tr>
                                            <tr>
                                                <td>chauffage</td>
                                                <td>{% if propriete.chauffage == 0 %}Oui{% else %}Non{% endif %}</td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="bg-gray py-2 px-3 mt-4">
                                <h2 class="mb-0">
                                    {{propriete.prixFormatter}} Fcfa
                                </h2>
                            </div>
                            <div>
                                 {{ include('backoffice/admin_propriete/_delete_form.html.twig') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}